name: Docker Image Build
on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: sk4redflaskapp.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t sk4redflaskapp.azurecr.io/simple-flask-app:${{ github.sha }}
        docker push sk4redflaskapp.azurecr.io/simple-flask-app:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'simple-flask-app'
        images: 'sk4redflaskapp.azurecr.io/simple-flask-app:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
