name: MNS Docker Image Build
on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    - name: 'Build and Push Docker Image'
      uses: DigitalInnovation/cloud-devsecops-pipelineactions/workflows/CI/push_image@latest
      with:
        cr_imagename: 'flask-sk4red' 
        cr_imagetag: ${{ github.run_id }}
        cr_username: ${{ secrets.ACR_USER }} 
        cr_password: ${{ secrets.ACR_PASS }} 
        cr_servername: ${{ secrets.ACR_SERVER }} 
        cr_dockerfile_name: Dockerfile 
        cr_dockerfile_path: ci-helper/ 
        cr_subscription: ${{ secrets.ACR_subscription }} 
        cr_tenant: ${{ secrets.ACR_tenant }} 
